ALTER TABLE reports ADD COLUMN IF NOT EXISTS score_riesgo DOUBLE PRECISION;
ALTER TABLE reports ADD COLUMN IF NOT EXISTS imagen_consistente BOOLEAN;
ALTER TABLE reports ADD COLUMN IF NOT EXISTS observacion_imagen TEXT;
ALTER TABLE reports ADD COLUMN IF NOT EXISTS reportes_similares INT;
ALTER TABLE reports ALTER COLUMN embedding TYPE VECTOR(768);
